apiVersion: v1
kind: Service
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
  labels:
    app: kubecost
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cost-analyzer
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 1032  # Custom No