name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "terraform/**"
      - "variables.tf"
      - "outputs.tf"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production # Set this in GitHub repo settings with reviewers for manual approval

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan File
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Manual approval before apply
        if: github.event_name == 'push'
        uses: peter-evans/manual-approval@v2
        with:
          reviewers: gurpreet2828 # Change to your GitHub username or team

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan
