name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "terraform/**"
      - "terraform-aws/**"
      - "deploy-sock-shop/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Prepare placeholder join_command.sh
        run: |
          mkdir -p terraform-aws/scripts
          echo '#!/bin/bash' > terraform-aws/scripts/join_command.sh
          echo 'echo "This is a placeholder join command script."' >> terraform-aws/scripts/join_command.sh
          chmod +x terraform-aws/scripts/join_command.sh

      - name: Prepare placeholder for helm chart
        run: |
          mkdir -p terraform-aws/scripts
          echo '#!/bin/bash' > terraform-aws/scripts/helm_install.sh
          echo 'echo "This is a placeholder Helm install script."' >> terraform-aws/scripts/helm_install.sh
          chmod +x terraform-aws/scripts/helm_install.sh

      - name: Setup SSH Key for Provisioners
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/docker
          chmod 600 ~/.ssh/docker
          echo "${{ secrets.JENKINS_SSH_PRIVATE_KEY }}" > ~/.ssh/jenkins_key
          chmod 600 ~/.ssh/jenkins_key

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan

      - name: Upload Plan File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        env:
          TF_VAR_ssh_key_private: ~/.ssh/docker
          TF_VAR_jenkins_key_private: ~/.ssh/jenkins_key
        run: terraform apply -auto-approve tfplan

      - name: Save master IP
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: terraform output -raw k8s_master_ip > ip.txt

      - name: Upload Master IP Artifact
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: master-ip
          path: ip.txt
