name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "terraform/**"
      - "terraform-aws/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/docker
          chmod 600 ~/.ssh/docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan with Exit Code Handling
        run: |
          terraform plan -out=tfplan
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 0 ]; then
            echo "Terraform plan succeeded with no changes."
            exit 0
          elif [ $EXIT_CODE -eq 2 ]; then
            echo "Terraform CLI exited with code 2 (deprecated)."
            exit 2
          elif [ $EXIT_CODE -eq 3 ]; then
            echo "Terraform plan completed successfully with changes."
            exit 0
          else
            echo "Terraform plan failed with error (exit code $EXIT_CODE)."
            exit 1
          fi

      - name: Upload Plan File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        env:
          TF_VAR_ssh_key_private: ~/.ssh/docker
        run: terraform apply -auto-approve tfplan
