name: Terraform CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "terraform/**"
      - "terraform-aws/**"
      - "deploy-sock-shop/**"
      - ".github/workflows/terraform-deploy.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  init:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Prepare placeholder join_command.sh
        run: |
          mkdir -p terraform-aws/scripts
          echo '#!/bin/bash' > terraform-aws/scripts/join_command.sh
          echo 'echo "This is a placeholder join command script."' >> terraform-aws/scripts/join_command.sh
          chmod +x terraform-aws/scripts/join_command.sh

      - name: Prepare placeholder for helm chart
        run: |
          mkdir -p terraform-aws/scripts
          echo '#!/bin/bash' > terraform-aws/scripts/helm_install.sh
          echo 'echo "This is a placeholder Helm install script."' >> terraform-aws/scripts/helm_install.sh
          chmod +x terraform-aws/scripts/helm_install.sh

      - name: Setup SSH Key for EC2 K8s Infrastructure
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/docker
          chmod 600 ~/.ssh/docker

      - name: Setup SSH Key for Jenkins
        run: |
          mkdir -p ~/.ssh    
          echo "${{ secrets.JENKINS_KEY_PRIVATE }}" > ~/.ssh/jenkins_key
          chmod 600 ~/.ssh/jenkins_key

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -reconfigure

  validate:
    needs: init
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

  plan:
    needs: validate
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    needs: plan
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}

    runs-on: ubuntu-latest
    environment: production

    env:
      TF_VAR_ssh_key_private: ~/.ssh/docker
      TF_VAR_jenkins_key_private: ~/.ssh/jenkins_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key for EC2 K8s Infrastructure
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/docker
          chmod 600 ~/.ssh/docker

      - name: Setup SSH Key for Jenkins
        run: |
          mkdir -p ~/.ssh    
          echo "${{ secrets.JENKINS_KEY_PRIVATE }}" > ~/.ssh/jenkins_key
          chmod 600 ~/.ssh/jenkins_key

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Save URLs and SSH info to file
        run: |
          echo "=== Terraform Outputs ===" > urls.txt

          # App URL
          echo "App NodePort URL: $(terraform output -raw deployment_app_nodeport_url)" >> urls.txt

          # Jenkins URL (safe fallback if output not available)
          echo "Jenkins URL: $(terraform output -raw jenkins_instance_info 2>/dev/null || echo 'N/A')" >> urls.txt

          # Grafana and Prometheus URLs (safe fallback)
          echo "Grafana URL: $(terraform output -raw grafana_url 2>/dev/null || echo 'N/A')" >> urls.txt
          echo "Prometheus URL: $(terraform output -raw prometheus_url 2>/dev/null || echo 'N/A')" >> urls.txt

          # ALB DNS
          echo "K8s ALB DNS: $(terraform output -raw k8s_alb_dns_name)" >> urls.txt

          echo "" >> urls.txt
          echo "=== SSH Connection Details ===" >> urls.txt

          # Master Node SSH
          echo "Master: $(terraform output -raw k8s_master_ssh_command 2>/dev/null || echo 'N/A')" >> urls.txt

          # Worker Node SSH commands
          echo "Worker Nodes:" >> urls.txt
          terraform output -json k8s_worker_connection_info 2>/dev/null | jq -r '.[] | "\(.tags.Name): \(.ssh_command)"' >> urls.txt || echo "N/A" >> urls.txt

      - name: Upload URLs artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-urls
          path: urls.txt

      - name: Cleanup
        run: |
          rm -f ~/.ssh/docker
          rm -f ~/.ssh/jenkins_key
          rm -f tfplan
          rm -f urls.txt

      - name: Notify Deployment Success
        run: |
          echo "Deployment successful! URLs and SSH info saved to urls.txt."
          echo "You can download the URLs artifact from the Actions tab."
