name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "terraform/**"
      - "terraform-aws/**"
      - "deploy-sock-shop/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git Safe Directory (to avoid errors)
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # Prepare placeholder join_command.sh file
      - name: Prepare placeholder join_command.sh file
        run: |
          mkdir -p terraform-aws/scripts
          echo '#!/bin/bash' > terraform-aws/scripts/join_command.sh
          echo 'echo "This is a placeholder join command script."' >> terraform-aws/scripts/join_command.sh
          chmod +x terraform-aws/scripts/join_command.sh

      # Prepare placeholder sock-shop deployment YAML
      - name: Prepare placeholder sock-shop deployment YAML
        run: |
          mkdir -p deploy-sock-shop/kubernetes
          cat > deploy-sock-shop/kubernetes/sock-shop-full-deployment.yaml <<EOF
          apiVersion: v1
          kind: Pod
          metadata:
            name: placeholder
          spec:
            containers:
            - name: placeholder
              image: busybox
              command: ["sleep", "3600"]
          EOF

      # Setup SSH private key for Terraform provisioners
      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/docker
          chmod 600 ~/.ssh/docker

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan with Exit Code Handling
        run: |
          terraform plan -out=tfplan
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 0 ]; then
            echo "Terraform plan succeeded with no changes."
            exit 0
          elif [ $EXIT_CODE -eq 2 ]; then
            echo "Terraform CLI exited with code 2 (deprecated)."
            exit 2
          elif [ $EXIT_CODE -eq 3 ]; then
            echo "Terraform plan completed successfully with changes."
            exit 0
          else
            echo "Terraform plan failed with error (exit code $EXIT_CODE)."
            exit 1
          fi

      - name: Upload Plan File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        env:
          TF_VAR_ssh_key_private: ~/.ssh/docker
        run: terraform apply -auto-approve tfplan

  deploy_app:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create sock-shop namespace if missing
        run: |
          kubectl get namespace sock-shop || kubectl create namespace sock-shop

      - name: Deploy sock-shop app
        run: |
          kubectl apply -f deploy-sock-shop/kubernetes/sock-shop-full-deployment.yaml -n sock-shop

      - name: Wait for pods to be ready
        run: |
          kubectl wait --for=condition=Ready pods --all -n sock-shop --timeout=300s

      - name: List sock-shop pods
        run: kubectl get pods -n sock-shop
